#training setting
lr: 0.0001
min_lr: 0.00001
weight_decay: 0.00001 # l2 norm
patience: 1 # Number of epochs with no improvement after which learning rate will be reduced
es_patience: 2 #patience for early stop

#model config
trans_drop: 0.4
mlp_drop: 0.4
dropout: 0.4

epoch_correct: 3
weight_2: 1.0
num_interest: 8